---
title: "CLR processing round 2"
author: "Lev Tsypin"
output: html_document
---

Set up the environment

```{r}
setwd('~/Documents/git/TGN-2021/analysis/new_approach/CLR_MCL/')
library(parmigene)
library(igraph)
```

Load the data
```{r}
full <- read.csv(
  '../full_expr_consensus_round_1.csv',
  row.names = 1
  )

veg <- read.csv(
  '../veg_expr_consensus_round_1.csv',
  row.names = 1
)
sex <- read.csv(
  '../sex_expr_consensus_round_1.csv',
  row.names = 1
)
```

Check out what we have
```{r}
head(full)
head(veg)
head(sex)
```


Run CLR. Set the number of nearest neighbors to 5 so that the approach between CLR and UMAP is comparable.
```{r}
full.mut.info.mat <- knnmi.all(full, k=5)
full.clr.mat <- clr(full.mut.info.mat)

save(full.clr.mat, file='./full_filt_norm_CLR_2.RData')

veg.mut.info.mat <- knnmi.all(veg, k=5)
veg.clr.mat <- clr(veg.mut.info.mat)

save(veg.clr.mat, file='./veg_filt_norm_CLR_2.RData')

sex.mut.info.mat <- knnmi.all(sex, k=5)
sex.clr.mat <- clr(sex.mut.info.mat)

save(sex.clr.mat, file='./sex_filt_norm_CLR_2.RData')


```


Save the CLR matrices in .ncol graph format for feeding into the MCL algorithm
```{r}
full.graph <- graph_from_adjacency_matrix(full.clr.mat, 
                                          mode='undirected',
                                          weighted=TRUE
                                          )

veg.graph <- graph_from_adjacency_matrix(veg.clr.mat, 
                                          mode='undirected',
                                          weighted=TRUE
                                          )

sex.graph <- graph_from_adjacency_matrix(sex.clr.mat, 
                                          mode='undirected',
                                          weighted=TRUE
                                          )

write.graph(full.graph, './full_clr_graph_round_2.ncol', format='ncol')
write.graph(veg.graph, './veg_clr_graph_round_2.ncol', format='ncol')
write.graph(sex.graph, './sex_clr_graph_round_2.ncol', format='ncol')
```

