---
title: "Performing RMA on corrected probes"
author: "Lev Tsypin"
date: "11/7/2021"
output: html_document
---

```{r}
library(oligo)
library(pdInfoBuilder)
library(ggplot2)
setwd('~/Documents/git/TGNE-2022/TGNE/microarray_QC/')
set.seed(42)
```

```{r}
seed <- new("NgsExpressionPDInfoPkgSeed",
              ndfFile='../../raw_data/2007-02-28_Tetrahymena_expr.ndf',
              xysFile='./C0_GSM285570.xys',
              author='Lev Tsypin',
              email='ltsypin@gmail.com',
              biocViews='Annotation Data',
              species='Tetrahymena thermophila')

makePdInfoPackage(seed, destDir = '.')
```


```{r}
install.packages('./pd.2007.02.28.tetrahymena.expr/', repos=NULL, type='source')
```

```{r}
library(pd.2007.02.28.tetrahymena.expr)
```

```{r}
xysFiles <- list.xysfiles('.')
expression.feature.set <- read.xysfiles(xysFiles, pkgname = 'pd.2007.02.28.tetrahymena.expr')
```

```{r}
raw.expression <- exprs(expression.feature.set)
boxplot(expression.feature.set, las=2)
hist(expression.feature.set)
```

```{r}
fit <- fitProbeLevelModel(expression.feature.set)
NUSE(fit, names=xysFiles, las=2, cex=0.001)
```


```{r}
xysFiles[c(6, 20, 21, 27, 37,44, 47, 48, 50, 55, 56, 64)]
```

Removing these chips will leave, C2, S12, and c15m (as was initially the case) 
without replicates. I think that they should be removed as well, for rigor 
of the analysis.
```{r}
xysFiles[c(13, 22, 49)]
```

```{r}
qc.files <- xysFiles[-c(6, 13, 20, 21, 22, 27, 37, 44, 47, 48, 49, 50, 55, 56, 64)]
qc.files
```

```{r}
qc.featureset <- read.xysfiles(qc.files, pkgname = 'pd.2007.02.28.tetrahymena.expr')
qc.raw.expression <- exprs(qc.featureset)
boxplot(qc.featureset, las=2)
hist(qc.featureset)
```


```{r}
qc.rma.corrected <- rma(qc.featureset)
boxplot(qc.rma.corrected, transfo=identity, las=2)
hist(qc.rma.corrected, transfo=identity)
```



```{r}
qc.rma.expression <- exprs(qc.rma.corrected)
write.csv(qc.rma.expression, './QC_probe_rma_values.csv')
```

This takes a while to run, but it helps to validate that the NUSE plot points
us straight to the chips that should be thrown away.
```{r}
image(expression.feature.set, transfo=rank)
```




```{r}
nuse <- NUSE(fit, type='values')
nuse.df <- stack(as.data.frame(nuse))
ggplot(nuse.df, aes(ind, values)) + 
  geom_boxplot() + 
  theme(axis.text.x = element_text(angle=90)) + 
  scale_y_continuous(limits=c(0.95, 1.1)) +
  geom_hline(yintercept=1, linetype='solid', color='red', size=0.5)
```



